---
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme 
title: Salt Lake Adaptive Robotics Program
description: information about robotics for people with intellectual disabilities
author:
  name:           Salt Lake Adaptive Robotics Program
  url:            https://desertsjade.github.io
  email:
